services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: server-app
    depends_on:
      - db
      - redis
    ports:
      - "${PORT:-8000}:8000"
    environment:
      - DB_HOST=db
      - REDIS_HOST=redis
      - NODE_ENV=${NODE_ENV:-development}
    env_file:
      - .env
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules 
  
  db:
    image: postgres:16
    restart: always
    container_name: postgres-db
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - .dbdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    restart: always
    container_name: redis-server
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    ports:
      - "6379:6379"
    volumes:
      - .redisdata:/data
